baseDir = '/groups/branson/bransonlab/kwaki/ForceData/calibration/20231103_calibration';
opencvMats = cellfun(@(x) load(fullfile(baseDir, x)), {'cam_02_opencv.mat', 'cam_12_opencv.mat'}, 'uniformoutput', false);

% have extrinsic parameters for camera 0->2 and 1->2. Need to create extrinsics for
% 0->1. 
R_02 = opencvMats{1}.R;
T_02 = opencvMats{1}.T;

R_12 = opencvMats{2}.R;
T_12 = opencvMats{2}.T;

% first create R_21 and T_21
R_21 = R_12';
T_21 = -R_21*T_12;

R_01 = R_21*R_02;
T_01 = R_21*T_02+T_21;

view1 = 0;
view2 = 1;

calib_struct = struct( ...
    "calib_name_left", "cam_" + num2str(view1), ...
    "calib_name_right", "cam_" + num2str(view2), ...
    "cam0_id", view1, ...
    "cam1_id", view2, ...
    "dX", 5, ...
    "nx", 512, ...
    "ny", 512, ...
    "fc_left", opencvMats{1}.fc_left, ...
    "cc_left", opencvMats{1}.cc_left, ...
    "alpha_c_left", opencvMats{1}.alpha_c_left, ...
    "kc_left", opencvMats{1}.kc_left, ...
    "fc_right", opencvMats{2}.fc_left, ...
    "cc_right", opencvMats{2}.cc_left, ...
    "alpha_c_right", opencvMats{2}.alpha_c_left, ...
    "kc_right", opencvMats{2}.kc_left, ...
    "om", rodrigues(R_01), ...
    "R", R_01, ...
    "T", T_01, ...
    "F", [], ...
    "active_images_left", [], ...
    "cc_left_error", 0, ...
    "cc_right_error", 0, ...
    "recompute_intrinsic_right", 1, ...
    "recompute_intrinsic_left", 1 ...
);
save(fullfile(baseDir, "/cam_" + num2str(view1) + num2str(view2) +"_opencv.mat"), "-struct", "calib_struct");
