winBasePath = 'X:\DataForAPT\JumpingMice\2023_08_VgatCtx_avgc50Plus_backToFibers\';
linBasePath = '/groups/branson/bransonlab/DataforAPT/JumpingMice/2023_08_VgatCtx_avgc50Plus_backToFibers';

convertPTRAPTWin2Lin(...
    '202308avgc_AS.lbl', ...
    winBasePath, linBasePath);
